<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\GeneratedDocumentType;

class GeneratedDocumentTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        GeneratedDocumentType::insert([
            [
                'id' => 1,
                'name' => 'Application Request Letter',
                'description' => 'Request Letter for LTP Application',
                'status' => 1
            ],
            [
                'id' => 2,
                'name' => 'Order of Payment',
                'description' => 'This document serves as the Order of Payment for the Local Transport Permit (LTP) Application, detailing the fees and charges applicable for processing.',
                'status' => 1
            ],
            [
                'id' => 3,
                'name' => 'Local Transport Permit',
                'description' => 'The Final output that is generated by the system.',
                'status' => 1
            ],
            [
                'id' => 4,
                'name' => 'Wildlife Inspection Report',
                'description' => 'This document is generated by the system and serves as the report for the wildlife inspection.',
                'status' => 1
            ]
        ]);
    }
}
